### ISSUE TITLE
Generate mask costs much time

### ISSUE THREAD

**Issue by bang123-box** [TongkunGuan/SIGA#2]
hello:
  after reading your paper, I want to use the  segment method to do some work also in the scene text recognition, but I find that at the training stage, to genergate the image mask cost much time, it will increase the training time.  I first think to generate the mask at loacl machine but the Sythe dataset has 15M images it also will takes a lots of days to generate all the masks.  so can I ask how you deal with the problem when you at the training.

**Comment by TongkunGuan** [comment]
We adopt parallel processing to generate the mask at the local machine.

**Comment by Video54367** [comment]
Are the image masks generated when you run the program? Why do I have to specify the data set of the image mask when I run it, otherwise I get an error?
Traceback (most recent call last):
  File "train.py", line 493, in <module>
    train(opt, log)
  File "train.py", line 261, in train
    image_tensors, labels, masks = train_loader.get_batch(ratio_iteration)
  File "/home/TIP/YangWei/SIGA-main/SIGA_R/dataset.py", line 88, in get_batch
    image, label, mask = self.data_loader_iter.next()
  File "/home/TIP/anaconda3/envs/SIGA/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/TIP/anaconda3/envs/SIGA/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/TIP/anaconda3/envs/SIGA/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/TIP/anaconda3/envs/SIGA/lib/python3.7/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/TIP/anaconda3/envs/SIGA/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/TIP/anaconda3/envs/SIGA/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/TIP/anaconda3/envs/SIGA/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/TIP/anaconda3/envs/SIGA/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 308, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/TIP/anaconda3/envs/SIGA/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 308, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/TIP/YangWei/SIGA-main/SIGA_R/dataset.py", line 212, in __getitem__
    with self.mask_env.begin(write=False) as mask_txn:
  File "/home/TIP/anaconda3/envs/SIGA/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 83, in __getattr__
    raise AttributeError
AttributeError

**Comment by Video54367** [comment]
Are the image masks generated when you run the program? Why do I have to specify the data set of the image mask when I run it, otherwise I get an error?
Traceback (most recent call last):
  File "train.py", line 493, in <module>
    train(opt, log)
  File "train.py", line 261, in train
    image_tensors, labels, masks = train_loader.get_batch(ratio_iteration)
  File "/home/TIP/sjdijs/SIGA-main/SIGA_R/dataset.py", line 88, in get_batch
    image, label, mask = self.data_loader_iter.next()
  File "/home/TIP/anaconda3/envs/SIGA/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/TIP/anaconda3/envs/SIGA/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/TIP/anaconda3/envs/SIGA/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/TIP/anaconda3/envs/SIGA/lib/python3.7/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/TIP/anaconda3/envs/SIGA/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/TIP/anaconda3/envs/SIGA/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/TIP/anaconda3/envs/SIGA/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/TIP/anaconda3/envs/SIGA/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 308, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/TIP/anaconda3/envs/SIGA/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 308, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/TIP/sjdijs/SIGA-main/SIGA_R/dataset.py", line 212, in __getitem__
    with self.mask_env.begin(write=False) as mask_txn:
  File "/home/TIP/anaconda3/envs/SIGA/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 83, in __getattr__
    raise AttributeError
AttributeError

**Comment by bang123-box** [comment]
thanks for answering me, but I did't find the parallel processing method to generate the mask at the local machine. Do you use the multiprocessing lib to achieve the parallel processing or other way？

**Comment by TongkunGuan** [comment]
We have added the mask generation codes.

**Comment by TongkunGuan** [comment]
> We have added the mask generation codes.

We have added the mask generation codes.
