### ISSUE TITLE
在调用 forward() 方法时，is_eval 参数被传递了多次

### ISSUE THREAD

**Issue by cuifeixiang** [TongkunGuan/SIGA#8]
您好，我在复现SIGA_T时，出现了参数多次传递的问题，请问是什么原因呢？
Traceback (most recent call last):
  File "/root/autodl-tmp/SIGA/SIGA_T/test.py", line 413, in <module>
    test(opt)
  File "/root/autodl-tmp/SIGA/SIGA_T/test.py", line 352, in test
    _, accuracy_by_best_model, _, _, _, _, _, _ = validation(
  File "/root/autodl-tmp/SIGA/SIGA_T/test.py", line 157, in validation
    model(image, None, target, None, None, is_eval=True)  # final
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/autodl-tmp/SIGA/SIGA_T/models.py", line 40, in forward
    prediction = self.mgp_str(input, mask, text, len_target, iteration, is_eval=is_eval)#
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() got multiple values for argument 'is_eval'

**Comment by TongkunGuan** [comment]
> 您好，我在复现SIGA_T时，出现了参数多次传递的问题，请问是什么原因呢？ Traceback (most recent call last): File "/root/autodl-tmp/SIGA/SIGA_T/test.py", line 413, in test(opt) File "/root/autodl-tmp/SIGA/SIGA_T/test.py", line 352, in test _, accuracy_by_best_model, _, _, _, _, _, _ = validation( File "/root/autodl-tmp/SIGA/SIGA_T/test.py", line 157, in validation model(image, None, target, None, None, is_eval=True) # final File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl result = self.forward(*input, **kwargs) File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward return self.module(*inputs[0], **kwargs[0]) File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl result = self.forward(*input, **kwargs) File "/root/autodl-tmp/SIGA/SIGA_T/models.py", line 40, in forward prediction = self.mgp_str(input, mask, text, len_target, iteration, is_eval=is_eval)# File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl result = self.forward(*input, **kwargs) TypeError: forward() got multiple values for argument 'is_eval'

Please refer to line 352 in test.py 
https://github.com/TongkunGuan/SIGA/blob/000921a9a1d0930cfc5bbb4bd00823baa91380b6/SIGA_T/test/test.py#L352

We don't add `is_eval=True`

**Comment by cuifeixiang** [comment]
Hello, I don't add is_eval=True, here is my code:    
  _, accuracy_by_best_model, _, _, _, _, _, _ = validation(
                model, criterion, evaluation_loader, converter, opt)

**Comment by cuifeixiang** [comment]
I haven't modified your code.

**Comment by TongkunGuan** [comment]
> I haven't modified your code.

You are right!

**Comment by TongkunGuan** [comment]
> ```
>   Hello, I don't add is_eval=True, here is my code:    
> ```
> 
> _, accuracy_by_best_model, _, _, _, _, _, _ = validation( model, criterion, evaluation_loader, converter, opt)

我现在已经没有这个虚拟环境了 从目前的代码上我暂时也看不出来问题出在哪 但可以看的出来这应该是一个基础的代码问题 你可以手动调试一下解决它

**Comment by cuifeixiang** [comment]
我尝试了很多方法都没有解决，所以才向您发出提问，非常感谢您在百忙之中进行回复。

**Comment by TongkunGuan** [comment]
> 我尝试了很多方法都没有解决，所以才向您发出提问，非常感谢您在百忙之中进行回复。

我觉得你可以在test.py的157行 开始逐步运行 直到程序跳到models.py的40行 看看is_eval的参数到底是怎么传的

**Comment by cuifeixiang** [comment]
我已经试过在此处Debug并输出is_eval，但是is_eval在此过程中只输出了一次，并没有发现多次传递，直到再次回到test（opt）开始报错。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tongkun ***@***.***&gt;; 
发送时间: 2024年9月11日(星期三) 中午12:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TongkunGuan/SIGA] 在调用 forward() 方法时，is_eval 参数被传递了多次 (Issue #8)














  
我尝试了很多方法都没有解决，所以才向您发出提问，非常感谢您在百忙之中进行回复。
  
我觉得你可以在test.py的157行 开始逐步运行 直到程序跳到models.py的40行 看看is_eval的参数到底是怎么传的

**Comment by TongkunGuan** [comment]
> 我已经试过在此处Debug并输出is_eval，但是is_eval在此过程中只输出了一次，并没有发现多次传递，直到再次回到test（opt）开始报错。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Tongkun ***@***.***&gt;; 发送时间: 2024年9月11日(星期三) 中午12:01 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [TongkunGuan/SIGA] 在调用 forward() 方法时，is_eval 参数被传递了多次 (Issue #8) 我尝试了很多方法都没有解决，所以才向您发出提问，非常感谢您在百忙之中进行回复。 我觉得你可以在test.py的157行 开始逐步运行 直到程序跳到models.py的40行 看看is_eval的参数到底是怎么传的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

换个思路 把is_eval全部取消掉 然后把相关的代码部分写死 看看呢？

**Comment by cuifeixiang** [comment]
那样会出现新的错误，传递的值不匹配




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tongkun ***@***.***&gt;; 
发送时间: 2024年9月12日(星期四) 下午5:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TongkunGuan/SIGA] 在调用 forward() 方法时，is_eval 参数被传递了多次 (Issue #8)














  
我已经试过在此处Debug并输出is_eval，但是is_eval在此过程中只输出了一次，并没有发现多次传递，直到再次回到test（opt）开始报错。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Tongkun @.&gt;; 发送时间: 2024年9月11日(星期三) 中午12:01 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [TongkunGuan/SIGA] 在调用 forward() 方法时，is_eval 参数被传递了多次 (Issue #8) 我尝试了很多方法都没有解决，所以才向您发出提问，非常感谢您在百忙之中进行回复。 我觉得你可以在test.py的157行 开始逐步运行 直到程序跳到models.py的40行 看看is_eval的参数到底是怎么传的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
换个思路 把is_eval全部取消掉 然后把相关的代码部分写死 看看呢？

**Comment by cuifeixiang** [comment]
您好，文章中提到的自监督文本分割代码是不是并没有提供啊？
